'use client';

import { AlertTriangle, Send, Clock, CheckCircle2, ShieldAlert } from 'lucide-react';
import { useState, useEffect } from 'react';
import { db } from '@/lib/firebase/config';
import { collection, onSnapshot, query, orderBy, limit, doc, updateDoc } from 'firebase/firestore';

const DEFAULT_ALERTS = [
  { id: 'a1', status: 'pending', severity: 'critical', sector: 'Sector 4 & 5', message: 'Severe flooding detected near River Basin. Evacuate to Bangalore Central Community Hall immediately.', createdAt: new Date().toISOString() },
  { id: 'a2', status: 'sent', severity: 'warning', sector: 'Sector 2', message: 'Water levels rising in East Valley. Stay alert and prepare for evacuation.', createdAt: new Date(Date.now() - 3600*1000).toISOString() },
  { id: 'a3', status: 'sent', severity: 'info', sector: 'All Sectors', message: 'Heavy rainfall expected over next 24 hours. Monitor updates.', createdAt: new Date(Date.now() - 7200*1000).toISOString() },
];

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<any[]>(DEFAULT_ALERTS);

  useEffect(() => {
    const q = query(collection(db, 'alerts'), orderBy('createdAt', 'desc'), limit(50));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const data = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      if (data.length > 0) {
        setAlerts(data);
      } else {
        setAlerts(DEFAULT_ALERTS);
      }
    }, (error) => {
      console.warn("Firestore error reading alerts, using defaults:", error);
      setAlerts(DEFAULT_ALERTS);
    });
    return () => unsubscribe();
  }, []);

  const handleApprove = async (id: string) => {
    try {
      await updateDoc(doc(db, 'alerts', id), { status: 'sent' });
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="space-y-6 transition-colors">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Emergency Alerts</h1>
          <p className="text-gray-500 dark:text-gray-400 text-sm mt-1">Review and approve AI-generated broadcast notifications.</p>
        </div>
        <button className="flex items-center px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded-lg transition shadow-lg shadow-red-500/20">
          <ShieldAlert size={16} className="mr-2" /> Compose Manual Alert
        </button>
      </div>

      <div className="bg-white dark:bg-gray-800/50 rounded-2xl border border-gray-200 dark:border-gray-800 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="bg-gray-50 dark:bg-gray-900/50 text-gray-600 dark:text-gray-400 font-medium border-b border-gray-200 dark:border-gray-800">
              <tr>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4">Severity</th>
                <th className="px-6 py-4">Target Sector</th>
                <th className="px-6 py-4">Message Preview</th>
                <th className="px-6 py-4">Generated</th>
                <th className="px-6 py-4 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 dark:divide-gray-800">
              {alerts.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-12 text-center text-gray-500">
                    No active emergency alerts generated by the simulation yet.
                  </td>
                </tr>
              ) : (
                alerts.map((alert) => (
                  <tr key={alert.id} className="hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors group">
                    <td className="px-6 py-4">
                      {alert.status === 'pending' ? (
                        <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800 dark:bg-yellow-500/20 dark:text-yellow-500">
                          <Clock size={12} className="mr-1" /> Pending Approval
                        </span>
                      ) : (
                        <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-500/20 dark:text-green-500">
                          <CheckCircle2 size={12} className="mr-1" /> Broadcasted
                        </span>
                      )}
                    </td>
                    <td className="px-6 py-4">
                      <span className={`inline-flex items-center text-xs font-bold uppercase ${
                        alert.severity?.toUpperCase() === 'CRITICAL' ? 'text-red-600 dark:text-red-400' : 
                        alert.severity?.toUpperCase() === 'SEVERE' ? 'text-orange-600 dark:text-orange-400' : 
                        'text-yellow-600 dark:text-yellow-400'
                      }`}>
                        <AlertTriangle size={14} className="mr-1.5" /> {alert.severity}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-gray-900 dark:text-gray-300 font-medium">
                      {alert.sector || 'All Sectors'}
                    </td>
                    <td className="px-6 py-4 text-gray-600 dark:text-gray-400 max-w-xs truncate" title={alert.message}>
                      {alert.message}
                    </td>
                    <td className="px-6 py-4 text-gray-500 dark:text-gray-500">
                      {alert.createdAt ? new Date(alert.createdAt).toLocaleTimeString() : 'Just now'}
                    </td>
                    <td className="px-6 py-4 text-right">
                      {alert.status === 'pending' ? (
                        <button 
                          onClick={() => handleApprove(alert.id)}
                          className="inline-flex items-center px-3 py-1.5 bg-blue-50 text-blue-600 hover:bg-blue-100 dark:bg-blue-600/10 dark:text-blue-400 dark:hover:bg-blue-600/20 text-xs font-semibold rounded-lg transition"
                        >
                          <Send size={14} className="mr-1.5" /> Approve
                        </button>
                      ) : (
                        <button className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 text-xs font-medium transition">
                          View Report
                        </button>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
