'use client';

import { useState, useEffect } from 'react';
import { 
  Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, BarElement,
  Title, Tooltip, Legend, Filler, ArcElement
} from 'chart.js';
import { Line, Bar, Doughnut } from 'react-chartjs-2';
import { BarChart2, TrendingUp, Download, Calendar } from 'lucide-react';
import { useTheme } from 'next-themes';
import { useSimulation } from '@/components/dashboard/SimulationProvider';

ChartJS.register(
  CategoryScale, LinearScale, PointElement, LineElement, BarElement, ArcElement,
  Title, Tooltip, Legend, Filler
);

export default function AnalyticsPage() {
  const { theme } = useTheme();
  const { simulationState } = useSimulation();
  
  const isDark = theme === 'dark';
  const gridColor = isDark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.05)';
  const tickColor = isDark ? '#9ca3af' : '#6b7280';

  const riskData = {
    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    datasets: [
      {
        label: 'Average Risk Score',
        data: [25, 30, 45, 80, 85, 60, 40],
        borderColor: 'rgb(59, 130, 246)',
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        fill: true,
        tension: 0.4,
      }
    ]
  };

  const accuracyData = {
    labels: ['Week 1', 'Week 2', 'Week 3', 'Week 4'],
    datasets: [
      {
        label: 'Model Accuracy (%)',
        data: [92, 94, 91, 96],
        backgroundColor: 'rgb(16, 185, 129)',
        borderRadius: 4,
      }
    ]
  };

  const alertData = {
    labels: ['Critical', 'High', 'Moderate'],
    datasets: [
      {
        data: [12, 45, 120],
        backgroundColor: [
          'rgb(239, 68, 68)',
          'rgb(249, 115, 22)',
          'rgb(234, 179, 8)'
        ],
        borderWidth: 0,
      }
    ]
  };

  const commonOptions = {
    responsive: true,
    plugins: { legend: { display: false } },
    scales: {
      y: { grid: { color: gridColor }, ticks: { color: tickColor } },
      x: { grid: { display: false }, ticks: { color: tickColor } }
    }
  };

  return (
    <div className="space-y-6 transition-colors">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">System Analytics</h1>
          <p className="text-gray-500 dark:text-gray-400 text-sm mt-1">Historical data, model accuracy, and system performance metrics.</p>
        </div>
        <div className="flex space-x-3">
          <button className="flex items-center px-4 py-2 bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300 text-sm font-medium rounded-lg transition border border-gray-200 dark:border-gray-700 shadow-sm">
            <Calendar size={16} className="mr-2" /> Last 30 Days
          </button>
          <button className="flex items-center px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium rounded-lg transition shadow-lg shadow-blue-500/20">
            <Download size={16} className="mr-2" /> Export PDF
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-white dark:bg-gray-800/50 rounded-2xl border border-gray-200 dark:border-gray-800 p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white flex items-center mb-6">
            <TrendingUp size={18} className="mr-2 text-blue-500" /> Historical Risk Analysis
          </h2>
          <div className="h-[300px]">
            <Line data={riskData} options={commonOptions} />
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800/50 rounded-2xl border border-gray-200 dark:border-gray-800 p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white flex items-center mb-6">
            <BarChart2 size={18} className="mr-2 text-green-500" /> Prediction Model Accuracy
          </h2>
          <div className="h-[300px]">
            <Bar data={accuracyData} options={{...commonOptions, scales: { y: { min: 80, max: 100, grid: { color: gridColor }, ticks: { color: tickColor } }, x: { grid: { display: false }, ticks: { color: tickColor } } }}} />
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800/50 rounded-2xl border border-gray-200 dark:border-gray-800 p-6 shadow-sm flex flex-col justify-center items-center">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white flex items-center mb-6 w-full">
            <BarChart2 size={18} className="mr-2 text-red-500" /> Alerts Generated by Severity
          </h2>
          <div className="h-[250px] w-full max-w-[250px]">
            <Doughnut 
              data={alertData} 
              options={{
                cutout: '75%',
                plugins: {
                  legend: { position: 'bottom', labels: { color: isDark ? '#d1d5db' : '#374151', padding: 20 } }
                }
              }} 
            />
          </div>
        </div>
        
        <div className="bg-white dark:bg-gray-800/50 rounded-2xl border border-gray-200 dark:border-gray-800 p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white flex items-center mb-6">
            <BarChart2 size={18} className="mr-2 text-purple-500" /> System Metrics summary
          </h2>
           <div className="grid grid-cols-2 gap-4">
             <div className="p-4 bg-gray-50 dark:bg-gray-900/50 rounded-xl border border-gray-100 dark:border-gray-800">
               <div className="text-sm text-gray-500 dark:text-gray-400 mb-1">Total Sensors Active</div>
               <div className="text-2xl font-bold text-gray-900 dark:text-white">1,248</div>
             </div>
             <div className="p-4 bg-gray-50 dark:bg-gray-900/50 rounded-xl border border-gray-100 dark:border-gray-800">
               <div className="text-sm text-gray-500 dark:text-gray-400 mb-1">Total Evacuations</div>
               <div className="text-2xl font-bold text-gray-900 dark:text-white">{simulationState.tick * 35}</div>
             </div>
             <div className="p-4 bg-gray-50 dark:bg-gray-900/50 rounded-xl border border-gray-100 dark:border-gray-800">
               <div className="text-sm text-gray-500 dark:text-gray-400 mb-1">Avg AI Response Time</div>
               <div className="text-2xl font-bold text-gray-900 dark:text-white">{simulationState.tick > 0 ? '412ms' : '0ms'}</div>
             </div>
             <div className="p-4 bg-gray-50 dark:bg-gray-900/50 rounded-xl border border-gray-100 dark:border-gray-800">
               <div className="text-sm text-gray-500 dark:text-gray-400 mb-1">System Load (Tick)</div>
               <div className="text-2xl font-bold text-gray-900 dark:text-white">{simulationState.tick}</div>
             </div>
          </div>
        </div>
      </div>
    </div>
  );
}
